### ISSUE TITLE
add my key

### ISSUE THREAD

**Issue by xgdgsc** [archlinuxcn/archlinuxcn-keyring#4]
pub key attached.
[xgdgsc.txt](https://github.com/archlinuxcn/archlinuxcn-keyring/files/202092/xgdgsc.txt)

I didn' t find any documentation on how to package signed packages for this repo. Do we just run the commands like lilac:
```
run_cmd(['gpg', '--pinentry-mode', 'loopback', '--passphrase', '', '--detach-sign', '--', pkg])
```
after build? Maybe we should update some wiki pages.

**Comment by lilydjwg** [comment]
No. You set up `makepkg.conf` and `makepkg` signs your packages. You can't ask lilac to sign for you; lilac will sign packages she has built on her own.

**Comment by xgdgsc** [comment]
I meant running the `gpg` commands after `sudo extra-*-build` commands. So we should run 'makepkg --sign' instead.

**Comment by lilydjwg** [comment]
If you are using devtools, just run your command to create a detached signature. But you are not supposed to sign your packages on the build machine, because you'll have to upload (or generate) your private key there. It's preferred you build and pull it to your own machine to sign.

And yes, your command is correct, just don't expect lilac to run that.

**Comment by xgdgsc** [comment]
I actually generated the key on the build machine, which seems more convenient for me.

**Comment by farseerfc** [comment]
Please register this key on a keyserver. 
Our [update-keys](https://github.com/archlinuxcn/archlinuxcn-keyring/blob/master/update-keys) script seems to perfer download these keys from keyserver by itself.

**Comment by xgdgsc** [comment]
Uploaded to https://pgp.mit.edu/pks/lookup?search=0x00e716120987a801cd25070828d10c49a44f261e&op=vindex .
